set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[0]}]

# set_property IOSTANDARD LVCMOS33 [get_ports {test_in[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {test_in[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {test_in[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {test_in[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {test_in[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {test_in[0]}]

set_property PACKAGE_PIN B4 [get_ports {uo_out[0]}]
set_property PACKAGE_PIN A4 [get_ports {uo_out[4]}]
set_property PACKAGE_PIN A5 [get_ports {uo_out[1]}]
set_property PACKAGE_PIN A6 [get_ports {uo_out[5]}]
set_property PACKAGE_PIN C7 [get_ports {uo_out[2]}]
set_property PACKAGE_PIN D8 [get_ports {uo_out[6]}]

set_property PACKAGE_PIN R13 [get_ports {ui_in[7]}]
set_property PACKAGE_PIN U18 [get_ports {ui_in[6]}]
set_property PACKAGE_PIN T18 [get_ports {ui_in[5]}]
set_property PACKAGE_PIN N17 [get_ports {ui_in[4]}]
set_property PACKAGE_PIN M17 [get_ports {ui_in[3]}]
set_property PACKAGE_PIN P17 [get_ports {ui_in[2]}]
set_property PACKAGE_PIN P18 [get_ports {ui_in[1]}]
set_property PACKAGE_PIN M18 [get_ports {ui_in[0]}]

# set_property PACKAGE_PIN U12 [get_ports {test_in[5]}]
# set_property PACKAGE_PIN H6 [get_ports {test_in[4]}]
# set_property PACKAGE_PIN T13 [get_ports {test_in[3]}]
# set_property PACKAGE_PIN R16 [get_ports {test_in[2]}]
# set_property PACKAGE_PIN U8 [get_ports {test_in[1]}]
# set_property PACKAGE_PIN T8 [get_ports {test_in[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[3]}]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN B11 [get_ports {uo_out[7]}]
set_property PACKAGE_PIN V10 [get_ports rst_n]
set_property PACKAGE_PIN B12 [get_ports {uo_out[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {uio_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_in[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[0]}]
# set_property DRIVE 12 [get_ports {uio_oe[7]}]
# set_property DRIVE 12 [get_ports {uio_oe[6]}]
# set_property DRIVE 12 [get_ports {uio_oe[5]}]
# set_property DRIVE 12 [get_ports {uio_oe[4]}]
# set_property DRIVE 12 [get_ports {uio_oe[3]}]
# set_property DRIVE 12 [get_ports {uio_oe[2]}]
# set_property DRIVE 12 [get_ports {uio_oe[1]}]
# set_property DRIVE 12 [get_ports {uio_oe[0]}]

# set_property PACKAGE_PIN J8 [get_ports {uio_out[7]}]
# set_property PULLTYPE PULLDOWN [get_ports {uio_out[6]}]
# set_property PULLTYPE PULLDOWN [get_ports {uio_out[5]}]
# set_property PULLTYPE PULLDOWN [get_ports {uio_out[4]}]
# set_property PULLTYPE PULLDOWN [get_ports {uio_out[3]}]
# set_property PULLTYPE PULLDOWN [get_ports {uio_out[2]}]
set_property PULLTYPE PULLDOWN [get_ports {uio_in[7]}]
set_property PULLTYPE PULLDOWN [get_ports {uio_in[6]}]
set_property PULLTYPE PULLDOWN [get_ports {uio_in[5]}]
set_property PULLTYPE PULLDOWN [get_ports {uio_in[4]}]
set_property PULLTYPE PULLDOWN [get_ports {uio_in[3]}]
set_property PULLTYPE PULLDOWN [get_ports {uio_in[2]}]
set_property PULLTYPE PULLDOWN [get_ports {uio_in[1]}]
set_property PULLTYPE PULLDOWN [get_ports {uio_in[0]}]
# set_property SLEW SLOW [get_ports {uio_oe[7]}]
# set_property SLEW SLOW [get_ports {uio_oe[6]}]
# set_property SLEW SLOW [get_ports {uio_oe[5]}]
# set_property SLEW SLOW [get_ports {uio_oe[4]}]
# set_property SLEW SLOW [get_ports {uio_oe[3]}]
# set_property SLEW SLOW [get_ports {uio_oe[2]}]
# set_property SLEW SLOW [get_ports {uio_oe[1]}]
# set_property SLEW SLOW [get_ports {uio_oe[0]}]

# set_property OFFCHIP_TERM NONE [get_ports uio_oe[7]]
# set_property OFFCHIP_TERM NONE [get_ports uio_oe[6]]
# set_property OFFCHIP_TERM NONE [get_ports uio_oe[5]]
# set_property OFFCHIP_TERM NONE [get_ports uio_oe[4]]
# set_property OFFCHIP_TERM NONE [get_ports uio_oe[3]]
# set_property OFFCHIP_TERM NONE [get_ports uio_oe[2]]
# set_property OFFCHIP_TERM NONE [get_ports uio_oe[1]]
# set_property OFFCHIP_TERM NONE [get_ports uio_oe[0]]
# set_property OFFCHIP_TERM NONE [get_ports uio_out[7]]
# set_property OFFCHIP_TERM NONE [get_ports uio_out[6]]
# set_property OFFCHIP_TERM NONE [get_ports uio_out[5]]
# set_property OFFCHIP_TERM NONE [get_ports uio_out[4]]
# set_property OFFCHIP_TERM NONE [get_ports uio_out[3]]
# set_property OFFCHIP_TERM NONE [get_ports uio_out[2]]
# set_property OFFCHIP_TERM NONE [get_ports uio_out[1]]
# set_property OFFCHIP_TERM NONE [get_ports uio_out[0]]
# set_property PULLTYPE PULLDOWN [get_ports {uio_out[1]}]
# set_property PULLTYPE PULLDOWN [get_ports {uio_out[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_oe[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uio_out[0]}]


set_property PACKAGE_PIN V11 [get_ports {uio_oe[0]}]
set_property PACKAGE_PIN V12 [get_ports {uio_oe[1]}]
set_property PACKAGE_PIN V14 [get_ports {uio_oe[2]}]
set_property PACKAGE_PIN V15 [get_ports {uio_oe[3]}]
set_property PACKAGE_PIN T16 [get_ports {uio_oe[4]}]
set_property PACKAGE_PIN U14 [get_ports {uio_oe[5]}]
set_property PACKAGE_PIN T15 [get_ports {uio_oe[6]}]
set_property PACKAGE_PIN V16 [get_ports {uio_oe[7]}]

set_property PACKAGE_PIN U16 [get_ports {uio_out[0]}]
set_property PACKAGE_PIN U17 [get_ports {uio_out[1]}]
set_property PACKAGE_PIN V17 [get_ports {uio_out[2]}]
set_property PACKAGE_PIN R18 [get_ports {uio_out[3]}]
set_property PACKAGE_PIN N14 [get_ports {uio_out[4]}]
set_property PACKAGE_PIN J13 [get_ports {uio_out[5]}]
set_property PACKAGE_PIN D12 [get_ports {uio_out[6]}]
set_property PACKAGE_PIN A11 [get_ports {uio_out[7]}]

set_property DRIVE 12 [get_ports {uio_out[7]}]
