name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@tt10
        with:
          flow: openlane2

      - name: Copy OpenLane logs out of container

        run: |
          mkdir -p ol2_logs
          cp -r ol2/*/openlane.log ol2_logs/ || true
          cp -r ol2/*/runs ol2_logs/ || true   # 每个 step 的 stdout.log 都在 runs 里

      - name: Upload OpenLane logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: openlane-full-log
          path: ol2_logs

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@tt10

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@tt10

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@tt10
